# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      
    - name: Instalando depencias
      run: yarn install
    
    - name: Executando build
      run: yarn run build
    
    - name: Executando testes unitário
      run: yarn test
      env:
        CI: true
    
    - name: Publicando modulos
      uses: JS-DevTools/npm-publish@v1
      with:
          package: dist/package.json
          token: ${{ secrets.NPM_TOKEN }}
